#
# This file is part of the linuxpy project
#
# Copyright (c) 2024 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

import pathlib

from linuxpy.codegen.base import CEnum, run

HEADERS = [
    "/usr/include/linux/fb.h",
]


TEMPLATE = """\
#
# This file is part of the linuxpy project
#
# Copyright (c) 2024 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by {name}
# Date: {date}
# System: {system}
# Release: {release}
# Version: {version}

import enum

from linuxpy.ioctl import IOR as _IOR, IOW as _IOW, IOWR as _IOWR
from linuxpy.ctypes import u8, u16, u32, cuint, cint, cchar, culong
from linuxpy.ctypes import Struct, Union, POINTER, cvoidp


{enums_body}


{structs_body}


{iocs_body}
"""

# macros from #define statements
MACRO_ENUMS = [
    CEnum("Type", "FB_TYPE_"),
    CEnum("Text", "FB_AUX_TEXT_"),
    CEnum("VGAPlanes", "FB_AUX_VGA_PLANES_"),
    CEnum("Visual", "FB_VISUAL_"),
    CEnum("Acceleration", "FB_ACCEL_"),
    CEnum("Sync", "FB_SYNC_", klass="IntFlag"),
    CEnum("VarMode", "FB_VMODE_", klass="IntFlag"),
    CEnum("Rotation", "FB_ROTATE_"),
    CEnum("VESABlank", "VESA_"),
    CEnum("VarBlank", "FB_VBLANK_", klass="IntFlag"),
    CEnum("Cursor", "FB_CUR_", klass="IntFlag"),
    CEnum("Capability", "FB_CAP_", klass="IntFlag"),
    CEnum("IOC", "FBIO"),
]


this_dir = pathlib.Path(__file__).parent


def main(output=this_dir.parent / "fb" / "raw.py"):
    import logging

    logging.basicConfig(level="DEBUG")
    run(__name__, HEADERS, TEMPLATE, MACRO_ENUMS, output=output)


if __name__ == "__main__":
    main()
