#
# This file is part of the linuxpy project
#
# Copyright (c) 2025 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by {name}
# Date: {date}
# System: {system}
# Release: {release}
# Version: {version}

from linuxpy.ctypes import Struct, u8, u16


class sockaddr(Struct):
    _fields_ = [
        ("sa_family", u16),
        ("sa_data", u8 * 14),
    ]
