#
# This file is part of the linuxpy project
#
# Copyright (c) 2024 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by __main__
# Date: 2024-10-08 20:52:50.241364
# System: Linux
# Release: 6.8.0-45-generic
# Version: #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024

import enum

from linuxpy.ctypes import Struct, cuint, culonglong, u8, u16, u32
from linuxpy.ioctl import IOR as _IOR, IOW as _IOW


class spi_ioc_transfer(Struct):
    pass


spi_ioc_transfer._fields_ = [
    ("tx_buf", culonglong),
    ("rx_buf", culonglong),
    ("len", cuint),
    ("speed_hz", cuint),
    ("delay_usecs", u16),
    ("bits_per_word", u8),
    ("cs_change", u8),
    ("tx_nbits", u8),
    ("rx_nbits", u8),
    ("word_delay_usecs", u8),
    ("pad", u8),
]


class IOC(enum.IntEnum):
    MAGIC = "k"
    RD_MODE = _IOR(MAGIC, 1, u8)
    WR_MODE = _IOW(MAGIC, 1, u8)
    RD_LSB_FIRST = _IOR(MAGIC, 2, u8)
    WR_LSB_FIRST = _IOW(MAGIC, 2, u8)
    RD_BITS_PER_WORD = _IOR(MAGIC, 3, u8)
    WR_BITS_PER_WORD = _IOW(MAGIC, 3, u8)
    RD_MAX_SPEED_HZ = _IOR(MAGIC, 4, u32)
    WR_MAX_SPEED_HZ = _IOW(MAGIC, 4, u32)
    RD_MODE32 = _IOR(MAGIC, 5, u32)
    WR_MODE32 = _IOW(MAGIC, 5, u32)
