#
# This file is part of the python-linux project
#
# Copyright (c) 2023 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by linux.media.video.gencodes
# Date: {date}
# Version: {version}

import collections


def struct_repr(self):
    name = type(self).__name__
    fields = ', '.join(('{{}}={{}}'.format(field[0], getattr(self, field[0]))
                        for field in self._fields_))
    return '{{}}({{}})'.format(name, fields)


def struct_asdict(self):
    r = collections.OrderedDict()
    for field_name, _ in self._fields_:
        r[field_name] = getattr(self, field_name)
    return r


def struct_iter(self):
    for fname, _ in self._fields_:
        yield getattr(self, fname)