# This file is part of the linuxpy project
#
# Copyright (c) 2023 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by linuxpy.codegen.usbids
# Date: 2024-07-30 06:58:39.981929
# System: Linux
# Release: 6.8.0-39-generic
# Version: #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024

audio_terminal = {
    256: {"name": "USB Undefined"},
    257: {"name": "USB Streaming"},
    511: {"name": "USB Vendor Specific"},
    512: {"name": "Input Undefined"},
    513: {"name": "Microphone"},
    514: {"name": "Desktop Microphone"},
    515: {"name": "Personal Microphone"},
    516: {"name": "Omni-directional Microphone"},
    517: {"name": "Microphone Array"},
    518: {"name": "Processing Microphone Array"},
    768: {"name": "Output Undefined"},
    769: {"name": "Speaker"},
    770: {"name": "Headphones"},
    771: {"name": "Head Mounted Display Audio"},
    772: {"name": "Desktop Speaker"},
    773: {"name": "Room Speaker"},
    774: {"name": "Communication Speaker"},
    775: {"name": "Low Frequency Effects Speaker"},
    1024: {"name": "Bidirectional Undefined"},
    1025: {"name": "Handset"},
    1026: {"name": "Headset"},
    1027: {"name": "Speakerphone, no echo reduction"},
    1028: {"name": "Echo-suppressing speakerphone"},
    1029: {"name": "Echo-canceling speakerphone"},
    1280: {"name": "Telephony Undefined"},
    1281: {"name": "Phone line"},
    1282: {"name": "Telephone"},
    1283: {"name": "Down Line Phone"},
    1536: {"name": "External Undefined"},
    1537: {"name": "Analog Connector"},
    1538: {"name": "Digital Audio Interface"},
    1539: {"name": "Line Connector"},
    1540: {"name": "Legacy Audio Connector"},
    1541: {"name": "SPDIF interface"},
    1542: {"name": "1394 DA stream"},
    1543: {"name": "1394 DV stream soundtrack"},
    1792: {"name": "Embedded Undefined"},
    1793: {"name": "Level Calibration Noise Source"},
    1794: {"name": "Equalization Noise"},
    1795: {"name": "CD Player"},
    1796: {"name": "DAT"},
    1797: {"name": "DCC"},
    1798: {"name": "MiniDisc"},
    1799: {"name": "Analog Tape"},
    1800: {"name": "Phonograph"},
    1801: {"name": "VCR Audio"},
    1802: {"name": "Video Disc Audio"},
    1803: {"name": "DVD Audio"},
    1804: {"name": "TV Tuner Audio"},
    1805: {"name": "Satellite Receiver Audio"},
    1806: {"name": "Cable Tuner Audio"},
    1807: {"name": "DSS Audio"},
    1808: {"name": "Radio Receiver"},
    1809: {"name": "Radio Transmitter"},
    1810: {"name": "Multitrack Recorder"},
    1811: {"name": "Synthesizer"},
}
