# This file is part of the linuxpy project
#
# Copyright (c) 2023 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by linuxpy.codegen.usbids
# Date: 2024-03-07 14:35:50.801033
# System: Linux
# Release: 6.5.13-1rodete2-amd64
# Version: #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1rodete2 (2024-01-11)

bias = {
    0: {"name": "Not Applicable"},
    1: {"name": "Right Hand"},
    2: {"name": "Left Hand"},
    3: {"name": "Both Hands"},
    4: {"name": "Either Hand"},
}
