# This file is part of the linuxpy project
#
# Copyright (c) 2023 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by linuxpy.codegen.usbids
# Date: 2024-07-30 06:58:40.020685
# System: Linux
# Release: 6.8.0-39-generic
# Version: #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024

bias = {
    0: {"name": "Not Applicable"},
    1: {"name": "Right Hand"},
    2: {"name": "Left Hand"},
    3: {"name": "Both Hands"},
    4: {"name": "Either Hand"},
}
