# This file is part of the linuxpy project
#
# Copyright (c) 2023 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by linuxpy.codegen.usbids
# Date: 2024-03-06 11:25:26.990417
# System: Linux
# Release: 6.5.0-21-generic
# Version: #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2

bias = {
    0: {"name": "Not Applicable"},
    1: {"name": "Right Hand"},
    2: {"name": "Left Hand"},
    3: {"name": "Both Hands"},
    4: {"name": "Either Hand"},
}
