# This file is part of the linuxpy project
#
# Copyright (c) 2023 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by linuxpy.codegen.usbids
# Date: 2024-07-30 06:58:40.119820
# System: Linux
# Release: 6.8.0-39-generic
# Version: #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024

country = {
    0: {"name": "Not supported"},
    1: {"name": "Arabic"},
    2: {"name": "Belgian"},
    3: {"name": "Canadian-Bilingual"},
    4: {"name": "Canadian-French"},
    5: {"name": "Czech Republic"},
    6: {"name": "Danish"},
    7: {"name": "Finnish"},
    8: {"name": "French"},
    9: {"name": "German"},
    16: {"name": "Greek"},
    17: {"name": "Hebrew"},
    18: {"name": "Hungary"},
    19: {"name": "International (ISO)"},
    20: {"name": "Italian"},
    21: {"name": "Japan (Katakana)"},
    22: {"name": "Korean"},
    23: {"name": "Latin American"},
    24: {"name": "Netherlands/Dutch"},
    25: {"name": "Norwegian"},
    32: {"name": "Persian (Farsi)"},
    33: {"name": "Poland"},
    34: {"name": "Portuguese"},
    35: {"name": "Russia"},
    36: {"name": "Slovakia"},
    37: {"name": "Spanish"},
    38: {"name": "Swedish"},
    39: {"name": "Swiss/French"},
    40: {"name": "Swiss/German"},
    41: {"name": "Switzerland"},
    48: {"name": "Taiwan"},
    49: {"name": "Turkish-Q"},
    50: {"name": "UK"},
    51: {"name": "US"},
    52: {"name": "Yugoslavia"},
    53: {"name": "Turkish-F"},
}
