# This file is part of the linuxpy project
#
# Copyright (c) 2023 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by linuxpy.codegen.usbids
# Date: 2024-01-13 06:16:03.881294
# System: Linux
# Release: 6.2.0-39-generic
# Version: #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2

hid = {33: {"name": "HID"}, 34: {"name": "Report"}, 35: {"name": "Physical"}}
