# This file is part of the linuxpy project
#
# Copyright (c) 2023 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by linuxpy.codegen.usbids
# Date: 2024-03-07 14:35:50.775675
# System: Linux
# Release: 6.5.13-1rodete2-amd64
# Version: #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1rodete2 (2024-01-11)

hid = {33: {"name": "HID"}, 34: {"name": "Report"}, 35: {"name": "Physical"}}
