# This file is part of the linuxpy project
#
# Copyright (c) 2023 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by linuxpy.codegen.usbids
# Date: 2024-07-30 06:58:40.007190
# System: Linux
# Release: 6.8.0-39-generic
# Version: #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024

hid_item = {
    4: {"name": "Usage Page"},
    8: {"name": "Usage"},
    20: {"name": "Logical Minimum"},
    24: {"name": "Usage Minimum"},
    36: {"name": "Logical Maximum"},
    40: {"name": "Usage Maximum"},
    52: {"name": "Physical Minimum"},
    56: {"name": "Designator Index"},
    68: {"name": "Physical Maximum"},
    72: {"name": "Designator Minimum"},
    84: {"name": "Unit Exponent"},
    88: {"name": "Designator Maximum"},
    100: {"name": "Unit"},
    116: {"name": "Report Size"},
    120: {"name": "String Index"},
    128: {"name": "Input"},
    132: {"name": "Report ID"},
    136: {"name": "String Minimum"},
    144: {"name": "Output"},
    148: {"name": "Report Count"},
    152: {"name": "String Maximum"},
    160: {"name": "Collection"},
    164: {"name": "Push"},
    168: {"name": "Delimiter"},
    176: {"name": "Feature"},
    180: {"name": "Pop"},
    192: {"name": "End Collection"},
}
