# This file is part of the linuxpy project
#
# Copyright (c) 2023 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by linuxpy.codegen.usbids
# Date: 2024-03-07 14:35:50.815797
# System: Linux
# Release: 6.5.13-1rodete2-amd64
# Version: #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1rodete2 (2024-01-11)

phy = {
    0: {"name": "None"},
    1: {"name": "Hand"},
    2: {"name": "Eyeball"},
    3: {"name": "Eyebrow"},
    4: {"name": "Eyelid"},
    5: {"name": "Ear"},
    6: {"name": "Nose"},
    7: {"name": "Mouth"},
    8: {"name": "Upper Lip"},
    9: {"name": "Lower Lip"},
    10: {"name": "Jaw"},
    11: {"name": "Neck"},
    12: {"name": "Upper Arm"},
    13: {"name": "Elbow"},
    14: {"name": "Forearm"},
    15: {"name": "Wrist"},
    16: {"name": "Palm"},
    17: {"name": "Thumb"},
    18: {"name": "Index Finger"},
    19: {"name": "Middle Finger"},
    20: {"name": "Ring Finger"},
    21: {"name": "Little Finger"},
    22: {"name": "Head"},
    23: {"name": "Shoulder"},
    24: {"name": "Hip"},
    25: {"name": "Waist"},
    26: {"name": "Thigh"},
    27: {"name": "Knee"},
    28: {"name": "calf"},
    29: {"name": "Ankle"},
    30: {"name": "Foot"},
    31: {"name": "Heel"},
    32: {"name": "Ball of Foot"},
    33: {"name": "Big Toe"},
    34: {"name": "Second Toe"},
    35: {"name": "Third Toe"},
    36: {"name": "Fourth Toe"},
    37: {"name": "Fifth Toe"},
    38: {"name": "Brow"},
    39: {"name": "Cheek"},
}
