# This file is part of the linuxpy project
#
# Copyright (c) 2023 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by linuxpy.codegen.usbids
# Date: 2024-03-07 14:35:50.905692
# System: Linux
# Release: 6.5.13-1rodete2-amd64
# Version: #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1rodete2 (2024-01-11)

video_terminal = {
    256: {"name": "USB Vendor Specific"},
    257: {"name": "USB Streaming"},
    512: {"name": "Input Vendor Specific"},
    513: {"name": "Camera Sensor"},
    514: {"name": "Sequential Media"},
    768: {"name": "Output Vendor Specific"},
    769: {"name": "Generic Display"},
    770: {"name": "Sequential Media"},
    1024: {"name": "External Vendor Specific"},
    1025: {"name": "Composite Video"},
    1026: {"name": "S-Video"},
    1027: {"name": "Component Video"},
}
