# This file is part of the linuxpy project
#
# Copyright (c) 2023 Tiago Coutinho
# Distributed under the GPLv3 license. See LICENSE for more info.

# This file has been generated by linuxpy.codegen.usbids
# Date: 2024-01-13 06:16:04.615842
# System: Linux
# Release: 6.2.0-39-generic
# Version: #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2

video_terminal = {
    256: {"name": "USB Vendor Specific"},
    257: {"name": "USB Streaming"},
    512: {"name": "Input Vendor Specific"},
    513: {"name": "Camera Sensor"},
    514: {"name": "Sequential Media"},
    768: {"name": "Output Vendor Specific"},
    769: {"name": "Generic Display"},
    770: {"name": "Sequential Media"},
    1024: {"name": "External Vendor Specific"},
    1025: {"name": "Composite Video"},
    1026: {"name": "S-Video"},
    1027: {"name": "Component Video"},
}
